### ISSUE TITLE
Better communication/Discord server

### ISSUE THREAD

**Issue by mechanikate** [Albert-Einholz/Einholzscher-Tech-Mod#11]
# Better communication/Discord server
### Feature:
A discord server for your mods

### Optional Alternative:
Some way to communicate about mods

## How voting works:
If you like the feature give THIS comment a thumb up. If you don't like the suggested feature or prefer the alternative over the feature give a thumb down. If you have additional suggestions or something else to say feel free to make a comment on this. After some time the feature will be implemented or discarded. Keep in mind that a feature may also be implemented if it receives more down-votes than up-votes or vise versa. This is only meant for finding out what you think is better the final decision will be made by me.

**Comment by 1holz** [comment]
https://discord.gg/FQanvZ6tkF

**Comment by mechanikate** [comment]
nice
